workflows:
  my-workflow:
    name: My Workflow
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release_ValeriiaIvanenko
          include: true
        - pattern: '*'
          include: false
    environment:
      groups:
        - fastlane
    scripts:
        - bundle install
        - bundle exec fastlane build_and_export animal:"CATS"
