# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and export to Firebase"
  lane :build_and_export do |options|
    set_info_plist_value(path: "./CatsAndModules-ValeriiaIvanenko-Info.plist", key: "Animal", value: options[:animal])
    gym
    firebase_app_distribution(
      app: "1:201152048872:ios:f1d2cc88d4b50d41b7235d",
      testers: "o.frankiv@ukma.edu.ua",
      release_notes: "Training with Fastlane"
    )
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:201152048872:ios:f1d2cc88d4b50d41b7235d"
    )
    increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
  end

  lane :take_screenshots do
    snapshot
  end
end
